platform :ios, '6.1'
pod 'OCMapper' 
pod 'SBJson'
pod 'ASIHTTPRequest'
pod 'EGOImageLoading'
pod 'OCMock', '~> 2.2.1'
pod 'GHUnitIOS', '~> 0.5.6'
pod 'PullTableView',:git => 'https://github.com/aiyuelian/PullDownRefreshAndPullUpLoadeMore'